ALTER TABLE ezz_drivers ADD COLUMN IF NOT EXISTS total_trips INTEGER DEFAULT 0;
ALTER TABLE ezz_drivers ADD COLUMN IF NOT EXISTS total_earnings DOUBLE PRECISION DEFAULT 0;
ALTER TABLE ezz_drivers ADD COLUMN IF NOT EXISTS total_commission_paid DOUBLE PRECISION DEFAULT 0;